[package]
name = "firn"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
kamadak-exif = "0.5.5"
tree_magic_mini = { version = "3.0.3", features = ["tree_magic_db", "with-gpl-data"] }

[profile.release]
debug = true
